config:
  # Runing mode
  #
  # - download: default mode, monitor URL and download when available
  # - metadata: download JSON metadata only
  # - notifier: only send notifications
  mode: download
  # There's no need to quote or escape your path, examples:
  #
  # - ~/Downlaods
  # - ~/Files/VTuber Videos
  # - ~/My Videos/Live Recordings
  #
  # All examples above should work
  output: ~/holoarchive/temp
  output_final: ~/holoarchive/archives
  interval: 20
  skip_alias: false
  skip_check: false
  skip_convert: false
  skip_metadata: false
  skip_email: false
  skip_slack: false
  skip_telegram: false
  one_time: false
  timezone: Asia/Tokyo
  email_provider: ses
  mailgun:
    # Find your private API key at https://app.mailgun.com/app/account/security/api_keys
    api: key-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    domain: mail.example.com
    receipt: me@example.com
  ses:
    access: AKxxxxxxxxxxxxxxxxxx
    secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    domain: mail.example.com
    receipt: me@example.com
  slack:
    # Create your webhook at https://slack.com/apps/A0F7XDUAZ-incoming-webhooks
    webhook: https://hooks.slack.com/services/
  telegram:
    # Obtian your bot API from @BotFather
    bot: 000000000:xxxxxxxxx
    # Get channel ID via:
    # https://api.telegram.org/bot<API-access-token>/getUpdates?offset=0
    channel: 0000000000000

map:
  - name: Mori Calliope
    youtube: https://www.youtube.com/channel/UCL_qhgtOy0dy1Agp8vkySQg

  - name: Takanashi Kiara
    youtube: https://www.youtube.com/channel/UCHsx4Hqa-1ORjQTh9TYDhww

  - name: Ninomae Inanis
    youtube: https://www.youtube.com/channel/UCMwGHR0BTZuLsmjY_NT5Pwg

  - name: Gawr Gura
    youtube: https://www.youtube.com/channel/UCoSrY_IQQVpmIRZ9Xf-y93g

  - name: Watson Amelia
    youtube: https://www.youtube.com/channel/UCyl1z3jo3XHR1riLFKG5UAg
   
  - name: Kiryu Coco
    youtube: https://www.youtube.com/channel/UCS9uQI-jC3DE0L4IpXyvr6w
